version = 1

[formatters.simple]
format = '%(asctime)s - %(name)-12s - %(levelname)-5s - %(message)s'

[handlers.console]
class = 'logging.StreamHandler'
level = 'INFO'
formatter = 'simple'
stream = 'ext://sys.stdout'

[handlers.file]
class = 'logging.handlers.RotatingFileHandler'
backupCount = 100
maxBytes = 1048576
level = 'INFO'
formatter = 'simple'
filename = 'logs/log'

[root]
level = 'DEBUG'
handlers = ['console', 'file']
