use crate::sim::Facing;
use std::ops::{Add, Mul, Sub};

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct Location {
    pub x: i16,
    pub y: i16,
}

pub type Distance = i16;
pub type DistanceSquared = i32;

impl Location {
    pub const fn new(x: i16, y: i16) -> Location {
        Location { x, y }
    }

    pub fn zero() -> Location {
        Location { x: 0, y: 0 }
    }

    pub fn distance(self, other: Self) -> Distance {
        (self.x - other.x).abs() + (self.y - other.y).abs()
    }

    pub fn lined_up(self, other: Self) -> bool {
        self.x == other.x || self.y == other.y
    }

    pub fn distance_squared(self, other: Self) -> DistanceSquared {
        let x_dist = (self.x - other.x).abs() as i32;
        let y_dist = (self.y - other.y).abs() as i32;
        x_dist * x_dist + y_dist * y_dist
    }

    pub fn rotate_around(self, center: Location, mut rotations: i8) -> Self {
        let vector = self - center;
        if rotations < 0 {
            rotations = 4 - rotations.abs();
        }
        match rotations {
            0 => self,
            1 => Location::new(-vector.y, vector.x) + center,
            2 => Location::new(-vector.x, -vector.y) + center,
            3 => Location::new(vector.y, -vector.x) + center,
            _ => unimplemented!("rotations -4..=3 supported"),
        }
    }

    pub fn facing_towards(self, other: Location) -> Facing {
        Facing::towards(self, other)
    }

    pub fn diamond(self, size: u8) -> DiamondIterator {
        DiamondIterator {
            iter: DIAMOND_PRECOMPUTED[(size as usize).min(DIAMOND_PRECOMPUTED.len() - 1)].iter(),
            constant: self,
        }
    }

    pub fn line(self, end: Location) -> LineIterator {
        let dx = (self.x - end.x).abs();
        let dy = -(self.y - end.y).abs();
        LineIterator {
            cur: self,
            end,
            dx,
            dy,
            sx: if self.x < end.x { 1 } else { -1 },
            sy: if self.y < end.y { 1 } else { -1 },
            err: dx + dy,
            done: false,
        }
    }
}

impl Add for Location {
    type Output = Self;

    fn add(self, other: Self) -> Self {
        Self {
            x: self.x + other.x,
            y: self.y + other.y,
        }
    }
}

impl Sub for Location {
    type Output = Self;

    fn sub(self, other: Self) -> Self {
        Self {
            x: self.x - other.x,
            y: self.y - other.y,
        }
    }
}

impl Mul<i16> for Location {
    type Output = Self;

    fn mul(self, other: i16) -> Self {
        Self {
            x: self.x * other,
            y: self.y * other,
        }
    }
}

pub struct DiamondIterator {
    iter: std::slice::Iter<'static, Location>,
    constant: Location,
}

impl Iterator for DiamondIterator {
    type Item = Location;

    fn next(&mut self) -> Option<Self::Item> {
        self.iter.next().map(|v| *v + self.constant)
    }
}

pub struct LineIterator {
    cur: Location,
    end: Location,
    dx: i16,
    dy: i16,
    sx: i16,
    sy: i16,
    err: i16,
    done: bool,
}

impl Iterator for LineIterator {
    type Item = Location;

    fn next(&mut self) -> Option<Self::Item> {
        if self.done {
            return None;
        }
        let ret = Some(self.cur);
        if self.cur == self.end {
            self.done = true;
            return ret;
        }
        let e2 = 2 * self.err;
        if e2 >= self.dy {
            self.err += self.dy;
            self.cur.x += self.sx;
        }
        if e2 <= self.dx {
            self.err += self.dx;
            self.cur.y += self.sy;
        }
        ret
    }
}

#[cfg(test)]
pub mod tests {
    use super::*;

    #[test]
    pub fn test_diamond_0() {
        let expected = vec![Location::zero()];
        let result: Vec<_> = Location::zero().diamond(0).collect();
        assert_eq!(expected, result);
    }

    #[test]
    pub fn test_diamond_1() {
        let expected = vec![
            Location::new(0, -1),
            Location::new(-1, 0),
            Location::zero(),
            Location::new(1, 0),
            Location::new(0, 1),
        ];
        let result: Vec<_> = Location::zero().diamond(1).collect();
        assert_eq!(expected, result);
    }

    #[test]
    pub fn test_rotations() {
        let vec1 = Location::new(2, 5);
        let center = Location::new(1, 1);
        assert_eq!(vec1.rotate_around(center, 0), vec1);

        let mut rotate1_twice = vec1;
        for _i in 1..=2 {
            rotate1_twice = rotate1_twice.rotate_around(center, 1);
        }
        assert_eq!(vec1.rotate_around(center, 2), rotate1_twice);

        let mut rotate1_thrice = vec1;
        for _i in 1..=3 {
            rotate1_thrice = rotate1_thrice.rotate_around(center, 1);
        }
        assert_eq!(vec1.rotate_around(center, 3), rotate1_thrice);
    }

    #[test]
    pub fn test_simple_line() {
        let start = Location::new(-2, 2);
        let end = Location::new(2, 2);
        let locations: Vec<_> = start.line(end).collect();
        assert_eq!(locations.len(), 5);
        for location in locations {
            assert!(start.lined_up(location));
        }
    }

    #[test]
    pub fn test_diag_line() {
        let start = Location::new(-2, -2);
        let end = Location::new(2, 2);
        let locations: Vec<_> = start.line(end).collect();
        assert_eq!(locations.len(), 5);
        for i in -2..=2 {
            assert!(locations.contains(&Location::new(i, i)));
        }
    }
}

const DIAMOND_PRECOMPUTED: &[&[Location]] = &[
    &[Location { x: 0, y: 0 }],
    &[
        Location { x: 0, y: -1 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 0, y: 1 },
    ],
    &[
        Location { x: 0, y: -2 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 0, y: 2 },
    ],
    &[
        Location { x: 0, y: -3 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 0, y: 3 },
    ],
    &[
        Location { x: 0, y: -4 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 0, y: 4 },
    ],
    &[
        Location { x: 0, y: -5 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 0, y: 5 },
    ],
    &[
        Location { x: 0, y: -6 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 0, y: 6 },
    ],
    &[
        Location { x: 0, y: -7 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 0, y: 7 },
    ],
    &[
        Location { x: 0, y: -8 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 0, y: 8 },
    ],
    &[
        Location { x: 0, y: -9 },
        Location { x: -1, y: -8 },
        Location { x: 0, y: -8 },
        Location { x: 1, y: -8 },
        Location { x: -2, y: -7 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: 2, y: -7 },
        Location { x: -3, y: -6 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: 3, y: -6 },
        Location { x: -4, y: -5 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: 4, y: -5 },
        Location { x: -5, y: -4 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: 5, y: -4 },
        Location { x: -6, y: -3 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: 6, y: -3 },
        Location { x: -7, y: -2 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: 7, y: -2 },
        Location { x: -8, y: -1 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: 8, y: -1 },
        Location { x: -9, y: 0 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: 9, y: 0 },
        Location { x: -8, y: 1 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: 8, y: 1 },
        Location { x: -7, y: 2 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: 7, y: 2 },
        Location { x: -6, y: 3 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: 6, y: 3 },
        Location { x: -5, y: 4 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: 5, y: 4 },
        Location { x: -4, y: 5 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: 4, y: 5 },
        Location { x: -3, y: 6 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: 3, y: 6 },
        Location { x: -2, y: 7 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 2, y: 7 },
        Location { x: -1, y: 8 },
        Location { x: 0, y: 8 },
        Location { x: 1, y: 8 },
        Location { x: 0, y: 9 },
    ],
    &[
        Location { x: 0, y: -10 },
        Location { x: -1, y: -9 },
        Location { x: 0, y: -9 },
        Location { x: 1, y: -9 },
        Location { x: -2, y: -8 },
        Location { x: -1, y: -8 },
        Location { x: 0, y: -8 },
        Location { x: 1, y: -8 },
        Location { x: 2, y: -8 },
        Location { x: -3, y: -7 },
        Location { x: -2, y: -7 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: 2, y: -7 },
        Location { x: 3, y: -7 },
        Location { x: -4, y: -6 },
        Location { x: -3, y: -6 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: 3, y: -6 },
        Location { x: 4, y: -6 },
        Location { x: -5, y: -5 },
        Location { x: -4, y: -5 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: 4, y: -5 },
        Location { x: 5, y: -5 },
        Location { x: -6, y: -4 },
        Location { x: -5, y: -4 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: 5, y: -4 },
        Location { x: 6, y: -4 },
        Location { x: -7, y: -3 },
        Location { x: -6, y: -3 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: 6, y: -3 },
        Location { x: 7, y: -3 },
        Location { x: -8, y: -2 },
        Location { x: -7, y: -2 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: 7, y: -2 },
        Location { x: 8, y: -2 },
        Location { x: -9, y: -1 },
        Location { x: -8, y: -1 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: 8, y: -1 },
        Location { x: 9, y: -1 },
        Location { x: -10, y: 0 },
        Location { x: -9, y: 0 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: 9, y: 0 },
        Location { x: 10, y: 0 },
        Location { x: -9, y: 1 },
        Location { x: -8, y: 1 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: 8, y: 1 },
        Location { x: 9, y: 1 },
        Location { x: -8, y: 2 },
        Location { x: -7, y: 2 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: 7, y: 2 },
        Location { x: 8, y: 2 },
        Location { x: -7, y: 3 },
        Location { x: -6, y: 3 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: 6, y: 3 },
        Location { x: 7, y: 3 },
        Location { x: -6, y: 4 },
        Location { x: -5, y: 4 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: 5, y: 4 },
        Location { x: 6, y: 4 },
        Location { x: -5, y: 5 },
        Location { x: -4, y: 5 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: 4, y: 5 },
        Location { x: 5, y: 5 },
        Location { x: -4, y: 6 },
        Location { x: -3, y: 6 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: 3, y: 6 },
        Location { x: 4, y: 6 },
        Location { x: -3, y: 7 },
        Location { x: -2, y: 7 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 2, y: 7 },
        Location { x: 3, y: 7 },
        Location { x: -2, y: 8 },
        Location { x: -1, y: 8 },
        Location { x: 0, y: 8 },
        Location { x: 1, y: 8 },
        Location { x: 2, y: 8 },
        Location { x: -1, y: 9 },
        Location { x: 0, y: 9 },
        Location { x: 1, y: 9 },
        Location { x: 0, y: 10 },
    ],
    &[
        Location { x: 0, y: -11 },
        Location { x: -1, y: -10 },
        Location { x: 0, y: -10 },
        Location { x: 1, y: -10 },
        Location { x: -2, y: -9 },
        Location { x: -1, y: -9 },
        Location { x: 0, y: -9 },
        Location { x: 1, y: -9 },
        Location { x: 2, y: -9 },
        Location { x: -3, y: -8 },
        Location { x: -2, y: -8 },
        Location { x: -1, y: -8 },
        Location { x: 0, y: -8 },
        Location { x: 1, y: -8 },
        Location { x: 2, y: -8 },
        Location { x: 3, y: -8 },
        Location { x: -4, y: -7 },
        Location { x: -3, y: -7 },
        Location { x: -2, y: -7 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: 2, y: -7 },
        Location { x: 3, y: -7 },
        Location { x: 4, y: -7 },
        Location { x: -5, y: -6 },
        Location { x: -4, y: -6 },
        Location { x: -3, y: -6 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: 3, y: -6 },
        Location { x: 4, y: -6 },
        Location { x: 5, y: -6 },
        Location { x: -6, y: -5 },
        Location { x: -5, y: -5 },
        Location { x: -4, y: -5 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: 4, y: -5 },
        Location { x: 5, y: -5 },
        Location { x: 6, y: -5 },
        Location { x: -7, y: -4 },
        Location { x: -6, y: -4 },
        Location { x: -5, y: -4 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: 5, y: -4 },
        Location { x: 6, y: -4 },
        Location { x: 7, y: -4 },
        Location { x: -8, y: -3 },
        Location { x: -7, y: -3 },
        Location { x: -6, y: -3 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: 6, y: -3 },
        Location { x: 7, y: -3 },
        Location { x: 8, y: -3 },
        Location { x: -9, y: -2 },
        Location { x: -8, y: -2 },
        Location { x: -7, y: -2 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: 7, y: -2 },
        Location { x: 8, y: -2 },
        Location { x: 9, y: -2 },
        Location { x: -10, y: -1 },
        Location { x: -9, y: -1 },
        Location { x: -8, y: -1 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: 8, y: -1 },
        Location { x: 9, y: -1 },
        Location { x: 10, y: -1 },
        Location { x: -11, y: 0 },
        Location { x: -10, y: 0 },
        Location { x: -9, y: 0 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: 9, y: 0 },
        Location { x: 10, y: 0 },
        Location { x: 11, y: 0 },
        Location { x: -10, y: 1 },
        Location { x: -9, y: 1 },
        Location { x: -8, y: 1 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: 8, y: 1 },
        Location { x: 9, y: 1 },
        Location { x: 10, y: 1 },
        Location { x: -9, y: 2 },
        Location { x: -8, y: 2 },
        Location { x: -7, y: 2 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: 7, y: 2 },
        Location { x: 8, y: 2 },
        Location { x: 9, y: 2 },
        Location { x: -8, y: 3 },
        Location { x: -7, y: 3 },
        Location { x: -6, y: 3 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: 6, y: 3 },
        Location { x: 7, y: 3 },
        Location { x: 8, y: 3 },
        Location { x: -7, y: 4 },
        Location { x: -6, y: 4 },
        Location { x: -5, y: 4 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: 5, y: 4 },
        Location { x: 6, y: 4 },
        Location { x: 7, y: 4 },
        Location { x: -6, y: 5 },
        Location { x: -5, y: 5 },
        Location { x: -4, y: 5 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: 4, y: 5 },
        Location { x: 5, y: 5 },
        Location { x: 6, y: 5 },
        Location { x: -5, y: 6 },
        Location { x: -4, y: 6 },
        Location { x: -3, y: 6 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: 3, y: 6 },
        Location { x: 4, y: 6 },
        Location { x: 5, y: 6 },
        Location { x: -4, y: 7 },
        Location { x: -3, y: 7 },
        Location { x: -2, y: 7 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 2, y: 7 },
        Location { x: 3, y: 7 },
        Location { x: 4, y: 7 },
        Location { x: -3, y: 8 },
        Location { x: -2, y: 8 },
        Location { x: -1, y: 8 },
        Location { x: 0, y: 8 },
        Location { x: 1, y: 8 },
        Location { x: 2, y: 8 },
        Location { x: 3, y: 8 },
        Location { x: -2, y: 9 },
        Location { x: -1, y: 9 },
        Location { x: 0, y: 9 },
        Location { x: 1, y: 9 },
        Location { x: 2, y: 9 },
        Location { x: -1, y: 10 },
        Location { x: 0, y: 10 },
        Location { x: 1, y: 10 },
        Location { x: 0, y: 11 },
    ],
];
