use std::ops::{Add, Mul, Sub};

#[derive(Copy, Clone, PartialEq, Eq, Debug)]
pub struct Location {
    pub x: i16,
    pub y: i16,
}

pub type Distance = i16;
pub type DistanceSquared = i32;

impl Location {
    pub const fn new(x: i16, y: i16) -> Location {
        Location { x, y }
    }

    pub fn zero() -> Location {
        Location { x: 0, y: 0 }
    }

    pub fn distance(self, other: Self) -> Distance {
        (self.x - other.x).abs() + (self.y - other.y).abs()
    }

    pub fn distance_squared(self, other: Self) -> DistanceSquared {
        let x_dist = (self.x - other.x).abs() as i32;
        let y_dist = (self.y - other.y).abs() as i32;
        x_dist * x_dist + y_dist * y_dist
    }

    pub fn diamond(self, size: u8) -> DiamondIterator {
        DiamondIterator {
            iter: DIAMOND_PRECOMPUTED[size as usize].iter(),
            constant: self,
        }
    }
}

impl Add for Location {
    type Output = Self;

    fn add(self, other: Self) -> Self {
        Self {
            x: self.x + other.x,
            y: self.y + other.y,
        }
    }
}

impl Sub for Location {
    type Output = Self;

    fn sub(self, other: Self) -> Self {
        Self {
            x: self.x - other.x,
            y: self.y - other.y,
        }
    }
}

impl Mul<i16> for Location {
    type Output = Self;

    fn mul(self, other: i16) -> Self {
        Self {
            x: self.x * other,
            y: self.y * other,
        }
    }
}

pub struct DiamondIterator {
    iter: std::slice::Iter<'static, Location>,
    constant: Location,
}

impl Iterator for DiamondIterator {
    type Item = Location;

    fn next(&mut self) -> Option<Self::Item> {
        self.iter.next().map(|v| *v + self.constant)
    }
}

// pub struct DiamondIterator {
//     size: u8,
//     idx: u16,
//     constant: Location,
// }
//
// // TODO: This implementation is going to be bare bones simple for now
// impl Iterator for DiamondIterator {
//     type Item = Location;
//
//     fn next(&mut self) -> Option<Self::Item> {
//         let length = (self.size * 2 + 1) as u16;
//         let squared = length * length;
//         while self.idx < squared {
//             let x = (self.idx % length) as i8 - self.size as i8;
//             let y = (self.idx / length) as i8 - self.size as i8;
//             let loc = Location::new(x as i16, y as i16);
//             self.idx += 1;
//             if Location::zero().distance(loc) <= self.size as i16 {
//                 return Some(loc + self.constant);
//             }
//         }
//         None
//     }
// }

#[cfg(test)]
pub mod tests {
    use super::*;

    #[test]
    pub fn test_diamond_0() {
        let expected = vec![Location::zero()];
        let result: Vec<_> = Location::zero().diamond(0).collect();
        assert_eq!(expected, result);
    }

    #[test]
    pub fn test_diamond_1() {
        let expected = vec![
            Location::new(0, -1),
            Location::new(-1, 0),
            Location::zero(),
            Location::new(1, 0),
            Location::new(0, 1),
        ];
        let result: Vec<_> = Location::zero().diamond(1).collect();
        assert_eq!(expected, result);
    }
}

const DIAMOND_PRECOMPUTED: &[&[Location]] = &[
    &[Location { x: 0, y: 0 }],
    &[
        Location { x: 0, y: -1 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 0, y: 1 },
    ],
    &[
        Location { x: 0, y: -2 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 0, y: 2 },
    ],
    &[
        Location { x: 0, y: -3 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 0, y: 3 },
    ],
    &[
        Location { x: 0, y: -4 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 0, y: 4 },
    ],
    &[
        Location { x: 0, y: -5 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 0, y: 5 },
    ],
    &[
        Location { x: 0, y: -6 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 0, y: 6 },
    ],
    &[
        Location { x: 0, y: -7 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 0, y: 7 },
    ],
    &[
        Location { x: 0, y: -8 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 0, y: 8 },
    ],
    &[
        Location { x: 0, y: -9 },
        Location { x: -1, y: -8 },
        Location { x: 0, y: -8 },
        Location { x: 1, y: -8 },
        Location { x: -2, y: -7 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: 2, y: -7 },
        Location { x: -3, y: -6 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: 3, y: -6 },
        Location { x: -4, y: -5 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: 4, y: -5 },
        Location { x: -5, y: -4 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: 5, y: -4 },
        Location { x: -6, y: -3 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: 6, y: -3 },
        Location { x: -7, y: -2 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: 7, y: -2 },
        Location { x: -8, y: -1 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: 8, y: -1 },
        Location { x: -9, y: 0 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: 9, y: 0 },
        Location { x: -8, y: 1 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: 8, y: 1 },
        Location { x: -7, y: 2 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: 7, y: 2 },
        Location { x: -6, y: 3 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: 6, y: 3 },
        Location { x: -5, y: 4 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: 5, y: 4 },
        Location { x: -4, y: 5 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: 4, y: 5 },
        Location { x: -3, y: 6 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: 3, y: 6 },
        Location { x: -2, y: 7 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 2, y: 7 },
        Location { x: -1, y: 8 },
        Location { x: 0, y: 8 },
        Location { x: 1, y: 8 },
        Location { x: 0, y: 9 },
    ],
    &[
        Location { x: 0, y: -10 },
        Location { x: -1, y: -9 },
        Location { x: 0, y: -9 },
        Location { x: 1, y: -9 },
        Location { x: -2, y: -8 },
        Location { x: -1, y: -8 },
        Location { x: 0, y: -8 },
        Location { x: 1, y: -8 },
        Location { x: 2, y: -8 },
        Location { x: -3, y: -7 },
        Location { x: -2, y: -7 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: 2, y: -7 },
        Location { x: 3, y: -7 },
        Location { x: -4, y: -6 },
        Location { x: -3, y: -6 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: 3, y: -6 },
        Location { x: 4, y: -6 },
        Location { x: -5, y: -5 },
        Location { x: -4, y: -5 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: 4, y: -5 },
        Location { x: 5, y: -5 },
        Location { x: -6, y: -4 },
        Location { x: -5, y: -4 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: 5, y: -4 },
        Location { x: 6, y: -4 },
        Location { x: -7, y: -3 },
        Location { x: -6, y: -3 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: 6, y: -3 },
        Location { x: 7, y: -3 },
        Location { x: -8, y: -2 },
        Location { x: -7, y: -2 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: 7, y: -2 },
        Location { x: 8, y: -2 },
        Location { x: -9, y: -1 },
        Location { x: -8, y: -1 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: 8, y: -1 },
        Location { x: 9, y: -1 },
        Location { x: -10, y: 0 },
        Location { x: -9, y: 0 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: 9, y: 0 },
        Location { x: 10, y: 0 },
        Location { x: -9, y: 1 },
        Location { x: -8, y: 1 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: 8, y: 1 },
        Location { x: 9, y: 1 },
        Location { x: -8, y: 2 },
        Location { x: -7, y: 2 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: 7, y: 2 },
        Location { x: 8, y: 2 },
        Location { x: -7, y: 3 },
        Location { x: -6, y: 3 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: 6, y: 3 },
        Location { x: 7, y: 3 },
        Location { x: -6, y: 4 },
        Location { x: -5, y: 4 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: 5, y: 4 },
        Location { x: 6, y: 4 },
        Location { x: -5, y: 5 },
        Location { x: -4, y: 5 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: 4, y: 5 },
        Location { x: 5, y: 5 },
        Location { x: -4, y: 6 },
        Location { x: -3, y: 6 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: 3, y: 6 },
        Location { x: 4, y: 6 },
        Location { x: -3, y: 7 },
        Location { x: -2, y: 7 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 2, y: 7 },
        Location { x: 3, y: 7 },
        Location { x: -2, y: 8 },
        Location { x: -1, y: 8 },
        Location { x: 0, y: 8 },
        Location { x: 1, y: 8 },
        Location { x: 2, y: 8 },
        Location { x: -1, y: 9 },
        Location { x: 0, y: 9 },
        Location { x: 1, y: 9 },
        Location { x: 0, y: 10 },
    ],
    &[
        Location { x: 0, y: -11 },
        Location { x: -1, y: -10 },
        Location { x: 0, y: -10 },
        Location { x: 1, y: -10 },
        Location { x: -2, y: -9 },
        Location { x: -1, y: -9 },
        Location { x: 0, y: -9 },
        Location { x: 1, y: -9 },
        Location { x: 2, y: -9 },
        Location { x: -3, y: -8 },
        Location { x: -2, y: -8 },
        Location { x: -1, y: -8 },
        Location { x: 0, y: -8 },
        Location { x: 1, y: -8 },
        Location { x: 2, y: -8 },
        Location { x: 3, y: -8 },
        Location { x: -4, y: -7 },
        Location { x: -3, y: -7 },
        Location { x: -2, y: -7 },
        Location { x: -1, y: -7 },
        Location { x: 0, y: -7 },
        Location { x: 1, y: -7 },
        Location { x: 2, y: -7 },
        Location { x: 3, y: -7 },
        Location { x: 4, y: -7 },
        Location { x: -5, y: -6 },
        Location { x: -4, y: -6 },
        Location { x: -3, y: -6 },
        Location { x: -2, y: -6 },
        Location { x: -1, y: -6 },
        Location { x: 0, y: -6 },
        Location { x: 1, y: -6 },
        Location { x: 2, y: -6 },
        Location { x: 3, y: -6 },
        Location { x: 4, y: -6 },
        Location { x: 5, y: -6 },
        Location { x: -6, y: -5 },
        Location { x: -5, y: -5 },
        Location { x: -4, y: -5 },
        Location { x: -3, y: -5 },
        Location { x: -2, y: -5 },
        Location { x: -1, y: -5 },
        Location { x: 0, y: -5 },
        Location { x: 1, y: -5 },
        Location { x: 2, y: -5 },
        Location { x: 3, y: -5 },
        Location { x: 4, y: -5 },
        Location { x: 5, y: -5 },
        Location { x: 6, y: -5 },
        Location { x: -7, y: -4 },
        Location { x: -6, y: -4 },
        Location { x: -5, y: -4 },
        Location { x: -4, y: -4 },
        Location { x: -3, y: -4 },
        Location { x: -2, y: -4 },
        Location { x: -1, y: -4 },
        Location { x: 0, y: -4 },
        Location { x: 1, y: -4 },
        Location { x: 2, y: -4 },
        Location { x: 3, y: -4 },
        Location { x: 4, y: -4 },
        Location { x: 5, y: -4 },
        Location { x: 6, y: -4 },
        Location { x: 7, y: -4 },
        Location { x: -8, y: -3 },
        Location { x: -7, y: -3 },
        Location { x: -6, y: -3 },
        Location { x: -5, y: -3 },
        Location { x: -4, y: -3 },
        Location { x: -3, y: -3 },
        Location { x: -2, y: -3 },
        Location { x: -1, y: -3 },
        Location { x: 0, y: -3 },
        Location { x: 1, y: -3 },
        Location { x: 2, y: -3 },
        Location { x: 3, y: -3 },
        Location { x: 4, y: -3 },
        Location { x: 5, y: -3 },
        Location { x: 6, y: -3 },
        Location { x: 7, y: -3 },
        Location { x: 8, y: -3 },
        Location { x: -9, y: -2 },
        Location { x: -8, y: -2 },
        Location { x: -7, y: -2 },
        Location { x: -6, y: -2 },
        Location { x: -5, y: -2 },
        Location { x: -4, y: -2 },
        Location { x: -3, y: -2 },
        Location { x: -2, y: -2 },
        Location { x: -1, y: -2 },
        Location { x: 0, y: -2 },
        Location { x: 1, y: -2 },
        Location { x: 2, y: -2 },
        Location { x: 3, y: -2 },
        Location { x: 4, y: -2 },
        Location { x: 5, y: -2 },
        Location { x: 6, y: -2 },
        Location { x: 7, y: -2 },
        Location { x: 8, y: -2 },
        Location { x: 9, y: -2 },
        Location { x: -10, y: -1 },
        Location { x: -9, y: -1 },
        Location { x: -8, y: -1 },
        Location { x: -7, y: -1 },
        Location { x: -6, y: -1 },
        Location { x: -5, y: -1 },
        Location { x: -4, y: -1 },
        Location { x: -3, y: -1 },
        Location { x: -2, y: -1 },
        Location { x: -1, y: -1 },
        Location { x: 0, y: -1 },
        Location { x: 1, y: -1 },
        Location { x: 2, y: -1 },
        Location { x: 3, y: -1 },
        Location { x: 4, y: -1 },
        Location { x: 5, y: -1 },
        Location { x: 6, y: -1 },
        Location { x: 7, y: -1 },
        Location { x: 8, y: -1 },
        Location { x: 9, y: -1 },
        Location { x: 10, y: -1 },
        Location { x: -11, y: 0 },
        Location { x: -10, y: 0 },
        Location { x: -9, y: 0 },
        Location { x: -8, y: 0 },
        Location { x: -7, y: 0 },
        Location { x: -6, y: 0 },
        Location { x: -5, y: 0 },
        Location { x: -4, y: 0 },
        Location { x: -3, y: 0 },
        Location { x: -2, y: 0 },
        Location { x: -1, y: 0 },
        Location { x: 0, y: 0 },
        Location { x: 1, y: 0 },
        Location { x: 2, y: 0 },
        Location { x: 3, y: 0 },
        Location { x: 4, y: 0 },
        Location { x: 5, y: 0 },
        Location { x: 6, y: 0 },
        Location { x: 7, y: 0 },
        Location { x: 8, y: 0 },
        Location { x: 9, y: 0 },
        Location { x: 10, y: 0 },
        Location { x: 11, y: 0 },
        Location { x: -10, y: 1 },
        Location { x: -9, y: 1 },
        Location { x: -8, y: 1 },
        Location { x: -7, y: 1 },
        Location { x: -6, y: 1 },
        Location { x: -5, y: 1 },
        Location { x: -4, y: 1 },
        Location { x: -3, y: 1 },
        Location { x: -2, y: 1 },
        Location { x: -1, y: 1 },
        Location { x: 0, y: 1 },
        Location { x: 1, y: 1 },
        Location { x: 2, y: 1 },
        Location { x: 3, y: 1 },
        Location { x: 4, y: 1 },
        Location { x: 5, y: 1 },
        Location { x: 6, y: 1 },
        Location { x: 7, y: 1 },
        Location { x: 8, y: 1 },
        Location { x: 9, y: 1 },
        Location { x: 10, y: 1 },
        Location { x: -9, y: 2 },
        Location { x: -8, y: 2 },
        Location { x: -7, y: 2 },
        Location { x: -6, y: 2 },
        Location { x: -5, y: 2 },
        Location { x: -4, y: 2 },
        Location { x: -3, y: 2 },
        Location { x: -2, y: 2 },
        Location { x: -1, y: 2 },
        Location { x: 0, y: 2 },
        Location { x: 1, y: 2 },
        Location { x: 2, y: 2 },
        Location { x: 3, y: 2 },
        Location { x: 4, y: 2 },
        Location { x: 5, y: 2 },
        Location { x: 6, y: 2 },
        Location { x: 7, y: 2 },
        Location { x: 8, y: 2 },
        Location { x: 9, y: 2 },
        Location { x: -8, y: 3 },
        Location { x: -7, y: 3 },
        Location { x: -6, y: 3 },
        Location { x: -5, y: 3 },
        Location { x: -4, y: 3 },
        Location { x: -3, y: 3 },
        Location { x: -2, y: 3 },
        Location { x: -1, y: 3 },
        Location { x: 0, y: 3 },
        Location { x: 1, y: 3 },
        Location { x: 2, y: 3 },
        Location { x: 3, y: 3 },
        Location { x: 4, y: 3 },
        Location { x: 5, y: 3 },
        Location { x: 6, y: 3 },
        Location { x: 7, y: 3 },
        Location { x: 8, y: 3 },
        Location { x: -7, y: 4 },
        Location { x: -6, y: 4 },
        Location { x: -5, y: 4 },
        Location { x: -4, y: 4 },
        Location { x: -3, y: 4 },
        Location { x: -2, y: 4 },
        Location { x: -1, y: 4 },
        Location { x: 0, y: 4 },
        Location { x: 1, y: 4 },
        Location { x: 2, y: 4 },
        Location { x: 3, y: 4 },
        Location { x: 4, y: 4 },
        Location { x: 5, y: 4 },
        Location { x: 6, y: 4 },
        Location { x: 7, y: 4 },
        Location { x: -6, y: 5 },
        Location { x: -5, y: 5 },
        Location { x: -4, y: 5 },
        Location { x: -3, y: 5 },
        Location { x: -2, y: 5 },
        Location { x: -1, y: 5 },
        Location { x: 0, y: 5 },
        Location { x: 1, y: 5 },
        Location { x: 2, y: 5 },
        Location { x: 3, y: 5 },
        Location { x: 4, y: 5 },
        Location { x: 5, y: 5 },
        Location { x: 6, y: 5 },
        Location { x: -5, y: 6 },
        Location { x: -4, y: 6 },
        Location { x: -3, y: 6 },
        Location { x: -2, y: 6 },
        Location { x: -1, y: 6 },
        Location { x: 0, y: 6 },
        Location { x: 1, y: 6 },
        Location { x: 2, y: 6 },
        Location { x: 3, y: 6 },
        Location { x: 4, y: 6 },
        Location { x: 5, y: 6 },
        Location { x: -4, y: 7 },
        Location { x: -3, y: 7 },
        Location { x: -2, y: 7 },
        Location { x: -1, y: 7 },
        Location { x: 0, y: 7 },
        Location { x: 1, y: 7 },
        Location { x: 2, y: 7 },
        Location { x: 3, y: 7 },
        Location { x: 4, y: 7 },
        Location { x: -3, y: 8 },
        Location { x: -2, y: 8 },
        Location { x: -1, y: 8 },
        Location { x: 0, y: 8 },
        Location { x: 1, y: 8 },
        Location { x: 2, y: 8 },
        Location { x: 3, y: 8 },
        Location { x: -2, y: 9 },
        Location { x: -1, y: 9 },
        Location { x: 0, y: 9 },
        Location { x: 1, y: 9 },
        Location { x: 2, y: 9 },
        Location { x: -1, y: 10 },
        Location { x: 0, y: 10 },
        Location { x: 1, y: 10 },
        Location { x: 0, y: 11 },
    ],
];
