name: Simulator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose --manifest-path simulator/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path simulator/Cargo.toml
